version: '3.9'

services:

  backend:
    build: ./go-backend
    environment:
      DB_HOST: host.docker.internal
      DB_PORT: 5432
      DB_USER: abdullah
      DB_PASSWORD: edhi
      DB_NAME: BookStore
    working_dir: /app
    ports: 
      - "8080:8080"
    networks:
      - goapp


  frontend:
    build: ./Bookstore-frontend/frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - goapp

volumes:
  pgdata:

networks:
  goapp:
